name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      uses: aleskxyz/build-push@v1
      with:
        image_name: ${{ vars.DOCKER_IMAGE }}:$(date +%s)
        registry_address: "docker.io/nchetelat"
        registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
