name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      uses: abhishek-070/docker-image-build-push-action@v1.0
      with:
        registry_url: "${{ vars.DOCKER_REGISTRY }}"
        repository_name: "${{ vars.DOCKER_IMAGE }}"
        user_name: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        image_version: '2.2'
        docker_file: '.'
